apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-job-delete
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8s-job-delete
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-job-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-job-delete
subjects:
  - kind: ServiceAccount
    name: k8s-job-delete
    namespace: default
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    qcloud-app: k8s-job-delete
  name: k8s-job-delete
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      qcloud-app: k8s-job-delete
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        qcloud-app: k8s-job-delete
    spec:
      containers:
      - args:
        - -c
        - python /python/examples/job-list.py
        command:
        - /bin/bash
        image: yan234280533/k8s-job-delete:v1.4
        imagePullPolicy: Always
        name: k8s-job-delete
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: Always
      securityContext: {}
      serviceAccountName: k8s-job-delete
      terminationGracePeriodSeconds: 30
      volumes: null
status: {}

